
# Create user configuration file
hxx{catch2/catch_user_config}: in{catch2/catch_user_config.hpp.in}

lib{catch2}: {hxx cxx}{** -catch2/internal/catch_main} hxx{catch2/catch_user_config}
lib{catch2wmain}: catch2/internal/cxx{catch_main} lib{catch2}


# Build options.
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$src_pfx_src" "-I$out_pfx_src"

cxx.export.poptions += "-I$src_pfx_src" "-I$out_pfx_src" 
lib{catch2wmain}: cxx.export.poptions += -DCATCH2_BUILD_STATIC_WITH_MAIN
lib{catch2wmain}: bin.whole = true

./: lib{catch2} lib{catch2wmain}

hxx{*}:
{
  install = include/
  install.subdirs = true
}
