intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{catch2}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DCATCH2_STATIC_BUILD
objs{*}: cxx.poptions += -DCATCH2_SHARED_BUILD

# Export options.
#
lib{catch2}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{catch2}: cxx.export.poptions += -DCATCH2_STATIC
libs{catch2}: cxx.export.poptions += -DCATCH2_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{catch2}: bin.lib.version = @"-$version.project_id"
else
  lib{catch2}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the catch2/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/catch2/
  install.subdirs = true
}
