import catch2_lib = catch2%lib{catch2}
./: exe{test}: cxx{test} $catch2_lib

if ($config.bin.lib == both || $config.bin.lib == static)
{
  import catch2_main_lib = catch2%liba{catch2wmain}
  ./: exe{testwmain}: cxx{test_w_staticlib} $catch2_main_lib
}

exe{*}: test = true