import intf_libs = catch2%liba{catch2}
import intf_libs =+ catch2%liba{catch2wmain}


./: exe{selftest}: {hxx cxx}{**} $intf_libs testscript Misc/file{*.input}
cxx.poptions += "-I$src_base/include"

# Need to ensure MSVC uses all strings as utf-8
# Required for "Broken String test"
if ($cxx.id == 'msvc')
  cxx.coptions += \/utf-8