import intf_libs = catch2%liba{catch2}
import intf_libs =+ catch2%liba{catch2wmain}


./: exe{selftest}: {hxx cxx}{**} $intf_libs testscript Misc/file{*.input}
cxx.poptions += "-I$src_base/include"

# Need to ensure MSVC uses all strings as utf-8
# Required for "Broken String test"
if ($cxx.id == 'msvc')
  cxx.coptions += \/utf-8

# On FreeBSD the auto detection of colour mode is not properly detected on console redirect
# There are colour codes written out which fails regex match
if($cxx.target.class == 'freebsd')
  exe{selftest}: test.options =+ --colour-mode none
